# Generated by Django 4.1.2 on 2022-11-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_service_delete_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="email",
            field=models.EmailField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
