# Generated by Django 4.1.2 on 2022-11-02 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_service_email_alter_service_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                (
                    "pickup_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("charge", models.CharField(max_length=50)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
            ],
        ),
        migrations.DeleteModel(name="Event",),
        migrations.AlterField(
            model_name="service",
            name="cleanup_time",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name="service",
            name="setup_time",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
